### ISSUE TITLE
strange python code or is it me??

### ISSUE THREAD

**Issue by PeterKenyon** [hosaka/micropython-st7735#2]
how does the power method work, shurely this isn't what was intended.
line 100 says self.power = state BUT self.power is the name of the method bizarre??

**Comment by hosaka** [comment]
You are correct! This is my mistake. This will execute, but will reassign the function to the state value. Well spotted, I'll fix it asap.

**Comment by hosaka** [comment]
Just to demonstrate the error:

``` python
>>> class Node():
...     power = 0
...     def power(self):
...             self.power = 5
...             return self.power
... 
>>> n = Node()
>>> n.power()
5
>>> n.power()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable
```

**Comment by PeterKenyon** [comment]
I saw you have changed this to use a backing variable power_on but doesn't that require it to be initialised somewhere, (also for backlight),

**Comment by hosaka** [comment]
They're both initialised in the [st7735.py#L64](https://github.com/hosaka/micropython-st7735/blob/master/st7735.py#L64). So when you inherit your class from TFT, your class will inherit those too.

**Comment by PeterKenyon** [comment]
oh OK, just keeping you on your toes  ;-)
